### ISSUE TITLE
Přežila metodika konverzi do MD?

### ISSUE THREAD

**Issue by michalradacz** [egdilna/metodiky-pristupnost-dokumentu#86]
@vladimirdvorakcz  podívej se na následující odkaz jestli vše je čitelné a přežilo, stačí si to projít jen tak v prohlížeči. Pak dej koment k tomuto issue a pokud je vše OK tak ho i zavři.

https://github.com/egdilna/metodiky-pristupnost-dokumentu/blob/michalradacz/issue85/metodika-pristupnost-dokumentu.md

**Comment by vladimirdvorakcz** [comment]
Metodika přežila převod do MD
